#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("XamProjectTemplate.Droid.Resource", IsApplication=true)]

namespace XamProjectTemplate.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Plugin.Media.Resource.Xml.xamarin_essentials_fileprovider_file_paths = global::XamProjectTemplate.Droid.Resource.Xml.xamarin_essentials_fileprovider_file_paths;
			global::Prism.Resource.Animation.EnterFromLeft = global::XamProjectTemplate.Droid.Resource.Animation.EnterFromLeft;
			global::Prism.Resource.Animation.EnterFromRight = global::XamProjectTemplate.Droid.Resource.Animation.EnterFromRight;
			global::Prism.Resource.Animation.ExitToLeft = global::XamProjectTemplate.Droid.Resource.Animation.ExitToLeft;
			global::Prism.Resource.Animation.ExitToRight = global::XamProjectTemplate.Droid.Resource.Animation.ExitToRight;
			global::Prism.Resource.Attribute.collectionViewStyle = global::XamProjectTemplate.Droid.Resource.Attribute.collectionViewStyle;
			global::Prism.Resource.Attribute.scrollViewStyle = global::XamProjectTemplate.Droid.Resource.Attribute.scrollViewStyle;
			global::Prism.Resource.Id.bottomtab_navarea = global::XamProjectTemplate.Droid.Resource.Id.bottomtab_navarea;
			global::Prism.Resource.Id.bottomtab_tabbar = global::XamProjectTemplate.Droid.Resource.Id.bottomtab_tabbar;
			global::Prism.Resource.Id.flyoutcontent_appbar = global::XamProjectTemplate.Droid.Resource.Id.flyoutcontent_appbar;
			global::Prism.Resource.Id.main_appbar = global::XamProjectTemplate.Droid.Resource.Id.main_appbar;
			global::Prism.Resource.Id.main_tablayout = global::XamProjectTemplate.Droid.Resource.Id.main_tablayout;
			global::Prism.Resource.Id.main_toolbar = global::XamProjectTemplate.Droid.Resource.Id.main_toolbar;
			global::Prism.Resource.Id.main_viewpager = global::XamProjectTemplate.Droid.Resource.Id.main_viewpager;
			global::Prism.Resource.Id.shellcontent_appbar = global::XamProjectTemplate.Droid.Resource.Id.shellcontent_appbar;
			global::Prism.Resource.Id.shellcontent_toolbar = global::XamProjectTemplate.Droid.Resource.Id.shellcontent_toolbar;
			global::Prism.Resource.Id.sliding_tabs = global::XamProjectTemplate.Droid.Resource.Id.sliding_tabs;
			global::Prism.Resource.Id.toolbar = global::XamProjectTemplate.Droid.Resource.Id.toolbar;
			global::Prism.Resource.Layout.BottomTabLayout = global::XamProjectTemplate.Droid.Resource.Layout.BottomTabLayout;
			global::Prism.Resource.Layout.FallbackTabbarDoNotUse = global::XamProjectTemplate.Droid.Resource.Layout.FallbackTabbarDoNotUse;
			global::Prism.Resource.Layout.FallbackToolbarDoNotUse = global::XamProjectTemplate.Droid.Resource.Layout.FallbackToolbarDoNotUse;
			global::Prism.Resource.Layout.FlyoutContent = global::XamProjectTemplate.Droid.Resource.Layout.FlyoutContent;
			global::Prism.Resource.Layout.RootLayout = global::XamProjectTemplate.Droid.Resource.Layout.RootLayout;
			global::Prism.Resource.Layout.ShellContent = global::XamProjectTemplate.Droid.Resource.Layout.ShellContent;
			global::Prism.Resource.Layout.Tabbar = global::XamProjectTemplate.Droid.Resource.Layout.Tabbar;
			global::Prism.Resource.Layout.Toolbar = global::XamProjectTemplate.Droid.Resource.Layout.Toolbar;
			global::Prism.Resource.String.overflow_tab_title = global::XamProjectTemplate.Droid.Resource.String.overflow_tab_title;
			global::Prism.Resource.Style.AppCompatDialogStyle = global::XamProjectTemplate.Droid.Resource.Style.AppCompatDialogStyle;
			global::Prism.Resource.Style.collectionViewTheme = global::XamProjectTemplate.Droid.Resource.Style.collectionViewTheme;
			global::Prism.Resource.Style.MainTheme = global::XamProjectTemplate.Droid.Resource.Style.MainTheme;
			global::Prism.Resource.Style.MainTheme_Base = global::XamProjectTemplate.Droid.Resource.Style.MainTheme_Base;
			global::Prism.Resource.Style.scrollViewScrollBars = global::XamProjectTemplate.Droid.Resource.Style.scrollViewScrollBars;
			global::Prism.Resource.Style.scrollViewTheme = global::XamProjectTemplate.Droid.Resource.Style.scrollViewTheme;
			global::Prism.Resource.Styleable.ItemsViewRendererTheme = global::XamProjectTemplate.Droid.Resource.Styleable.ItemsViewRendererTheme;
			global::Prism.Resource.Styleable.ItemsViewRendererTheme_collectionViewStyle = global::XamProjectTemplate.Droid.Resource.Styleable.ItemsViewRendererTheme_collectionViewStyle;
			global::Prism.Resource.Styleable.ScrollViewRendererTheme = global::XamProjectTemplate.Droid.Resource.Styleable.ScrollViewRendererTheme;
			global::Prism.Resource.Styleable.ScrollViewRendererTheme_scrollViewStyle = global::XamProjectTemplate.Droid.Resource.Styleable.ScrollViewRendererTheme_scrollViewStyle;
			global::Prism.Plugin.Popups.Resource.Animation.EnterFromLeft = global::XamProjectTemplate.Droid.Resource.Animation.EnterFromLeft;
			global::Prism.Plugin.Popups.Resource.Animation.EnterFromRight = global::XamProjectTemplate.Droid.Resource.Animation.EnterFromRight;
			global::Prism.Plugin.Popups.Resource.Animation.ExitToLeft = global::XamProjectTemplate.Droid.Resource.Animation.ExitToLeft;
			global::Prism.Plugin.Popups.Resource.Animation.ExitToRight = global::XamProjectTemplate.Droid.Resource.Animation.ExitToRight;
			global::Prism.Plugin.Popups.Resource.Attribute.collectionViewStyle = global::XamProjectTemplate.Droid.Resource.Attribute.collectionViewStyle;
			global::Prism.Plugin.Popups.Resource.Id.bottomtab_navarea = global::XamProjectTemplate.Droid.Resource.Id.bottomtab_navarea;
			global::Prism.Plugin.Popups.Resource.Id.bottomtab_tabbar = global::XamProjectTemplate.Droid.Resource.Id.bottomtab_tabbar;
			global::Prism.Plugin.Popups.Resource.Id.flyoutcontent_appbar = global::XamProjectTemplate.Droid.Resource.Id.flyoutcontent_appbar;
			global::Prism.Plugin.Popups.Resource.Id.main_appbar = global::XamProjectTemplate.Droid.Resource.Id.main_appbar;
			global::Prism.Plugin.Popups.Resource.Id.main_tablayout = global::XamProjectTemplate.Droid.Resource.Id.main_tablayout;
			global::Prism.Plugin.Popups.Resource.Id.main_toolbar = global::XamProjectTemplate.Droid.Resource.Id.main_toolbar;
			global::Prism.Plugin.Popups.Resource.Id.main_viewpager = global::XamProjectTemplate.Droid.Resource.Id.main_viewpager;
			global::Prism.Plugin.Popups.Resource.Id.shellcontent_appbar = global::XamProjectTemplate.Droid.Resource.Id.shellcontent_appbar;
			global::Prism.Plugin.Popups.Resource.Id.shellcontent_toolbar = global::XamProjectTemplate.Droid.Resource.Id.shellcontent_toolbar;
			global::Prism.Plugin.Popups.Resource.Id.sliding_tabs = global::XamProjectTemplate.Droid.Resource.Id.sliding_tabs;
			global::Prism.Plugin.Popups.Resource.Id.toolbar = global::XamProjectTemplate.Droid.Resource.Id.toolbar;
			global::Prism.Plugin.Popups.Resource.Layout.BottomTabLayout = global::XamProjectTemplate.Droid.Resource.Layout.BottomTabLayout;
			global::Prism.Plugin.Popups.Resource.Layout.FallbackTabbarDoNotUse = global::XamProjectTemplate.Droid.Resource.Layout.FallbackTabbarDoNotUse;
			global::Prism.Plugin.Popups.Resource.Layout.FallbackToolbarDoNotUse = global::XamProjectTemplate.Droid.Resource.Layout.FallbackToolbarDoNotUse;
			global::Prism.Plugin.Popups.Resource.Layout.FlyoutContent = global::XamProjectTemplate.Droid.Resource.Layout.FlyoutContent;
			global::Prism.Plugin.Popups.Resource.Layout.RootLayout = global::XamProjectTemplate.Droid.Resource.Layout.RootLayout;
			global::Prism.Plugin.Popups.Resource.Layout.ShellContent = global::XamProjectTemplate.Droid.Resource.Layout.ShellContent;
			global::Prism.Plugin.Popups.Resource.Layout.Tabbar = global::XamProjectTemplate.Droid.Resource.Layout.Tabbar;
			global::Prism.Plugin.Popups.Resource.Layout.Toolbar = global::XamProjectTemplate.Droid.Resource.Layout.Toolbar;
			global::Prism.Plugin.Popups.Resource.String.overflow_tab_title = global::XamProjectTemplate.Droid.Resource.String.overflow_tab_title;
			global::Prism.Plugin.Popups.Resource.Style.AppCompatDialogStyle = global::XamProjectTemplate.Droid.Resource.Style.AppCompatDialogStyle;
			global::Prism.Plugin.Popups.Resource.Style.collectionViewTheme = global::XamProjectTemplate.Droid.Resource.Style.collectionViewTheme;
			global::Prism.Plugin.Popups.Resource.Style.MainTheme = global::XamProjectTemplate.Droid.Resource.Style.MainTheme;
			global::Prism.Plugin.Popups.Resource.Style.MainTheme_Base = global::XamProjectTemplate.Droid.Resource.Style.MainTheme_Base;
			global::Prism.Plugin.Popups.Resource.Styleable.ItemsViewRendererTheme = global::XamProjectTemplate.Droid.Resource.Styleable.ItemsViewRendererTheme;
			global::Prism.Plugin.Popups.Resource.Styleable.ItemsViewRendererTheme_collectionViewStyle = global::XamProjectTemplate.Droid.Resource.Styleable.ItemsViewRendererTheme_collectionViewStyle;
			global::Rg.Plugins.Popup.Resource.Animation.EnterFromLeft = global::XamProjectTemplate.Droid.Resource.Animation.EnterFromLeft;
			global::Rg.Plugins.Popup.Resource.Animation.EnterFromRight = global::XamProjectTemplate.Droid.Resource.Animation.EnterFromRight;
			global::Rg.Plugins.Popup.Resource.Animation.ExitToLeft = global::XamProjectTemplate.Droid.Resource.Animation.ExitToLeft;
			global::Rg.Plugins.Popup.Resource.Animation.ExitToRight = global::XamProjectTemplate.Droid.Resource.Animation.ExitToRight;
			global::Rg.Plugins.Popup.Resource.Id.bottomtab_navarea = global::XamProjectTemplate.Droid.Resource.Id.bottomtab_navarea;
			global::Rg.Plugins.Popup.Resource.Id.bottomtab_tabbar = global::XamProjectTemplate.Droid.Resource.Id.bottomtab_tabbar;
			global::Rg.Plugins.Popup.Resource.Id.flyoutcontent_appbar = global::XamProjectTemplate.Droid.Resource.Id.flyoutcontent_appbar;
			global::Rg.Plugins.Popup.Resource.Id.main_appbar = global::XamProjectTemplate.Droid.Resource.Id.main_appbar;
			global::Rg.Plugins.Popup.Resource.Id.main_tablayout = global::XamProjectTemplate.Droid.Resource.Id.main_tablayout;
			global::Rg.Plugins.Popup.Resource.Id.main_toolbar = global::XamProjectTemplate.Droid.Resource.Id.main_toolbar;
			global::Rg.Plugins.Popup.Resource.Id.main_viewpager = global::XamProjectTemplate.Droid.Resource.Id.main_viewpager;
			global::Rg.Plugins.Popup.Resource.Id.shellcontent_appbar = global::XamProjectTemplate.Droid.Resource.Id.shellcontent_appbar;
			global::Rg.Plugins.Popup.Resource.Id.shellcontent_toolbar = global::XamProjectTemplate.Droid.Resource.Id.shellcontent_toolbar;
			global::Rg.Plugins.Popup.Resource.Id.sliding_tabs = global::XamProjectTemplate.Droid.Resource.Id.sliding_tabs;
			global::Rg.Plugins.Popup.Resource.Id.toolbar = global::XamProjectTemplate.Droid.Resource.Id.toolbar;
			global::Rg.Plugins.Popup.Resource.Layout.BottomTabLayout = global::XamProjectTemplate.Droid.Resource.Layout.BottomTabLayout;
			global::Rg.Plugins.Popup.Resource.Layout.FallbackTabbarDoNotUse = global::XamProjectTemplate.Droid.Resource.Layout.FallbackTabbarDoNotUse;
			global::Rg.Plugins.Popup.Resource.Layout.FallbackToolbarDoNotUse = global::XamProjectTemplate.Droid.Resource.Layout.FallbackToolbarDoNotUse;
			global::Rg.Plugins.Popup.Resource.Layout.FlyoutContent = global::XamProjectTemplate.Droid.Resource.Layout.FlyoutContent;
			global::Rg.Plugins.Popup.Resource.Layout.RootLayout = global::XamProjectTemplate.Droid.Resource.Layout.RootLayout;
			global::Rg.Plugins.Popup.Resource.Layout.ShellContent = global::XamProjectTemplate.Droid.Resource.Layout.ShellContent;
			global::Rg.Plugins.Popup.Resource.Layout.Tabbar = global::XamProjectTemplate.Droid.Resource.Layout.Tabbar;
			global::Rg.Plugins.Popup.Resource.Layout.Toolbar = global::XamProjectTemplate.Droid.Resource.Layout.Toolbar;
			global::Xamarin.Essentials.Resource.Xml.xamarin_essentials_fileprovider_file_paths = global::XamProjectTemplate.Droid.Resource.Xml.xamarin_essentials_fileprovider_file_paths;
			global::Xamarin.Forms.Platform.Android.Resource.Animation.EnterFromLeft = global::XamProjectTemplate.Droid.Resource.Animation.EnterFromLeft;
			global::Xamarin.Forms.Platform.Android.Resource.Animation.EnterFromRight = global::XamProjectTemplate.Droid.Resource.Animation.EnterFromRight;
			global::Xamarin.Forms.Platform.Android.Resource.Animation.ExitToLeft = global::XamProjectTemplate.Droid.Resource.Animation.ExitToLeft;
			global::Xamarin.Forms.Platform.Android.Resource.Animation.ExitToRight = global::XamProjectTemplate.Droid.Resource.Animation.ExitToRight;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.collectionViewStyle = global::XamProjectTemplate.Droid.Resource.Attribute.collectionViewStyle;
			global::Xamarin.Forms.Platform.Android.Resource.Attribute.scrollViewStyle = global::XamProjectTemplate.Droid.Resource.Attribute.scrollViewStyle;
			global::Xamarin.Forms.Platform.Android.Resource.Id.bottomtab_navarea = global::XamProjectTemplate.Droid.Resource.Id.bottomtab_navarea;
			global::Xamarin.Forms.Platform.Android.Resource.Id.bottomtab_tabbar = global::XamProjectTemplate.Droid.Resource.Id.bottomtab_tabbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.flyoutcontent_appbar = global::XamProjectTemplate.Droid.Resource.Id.flyoutcontent_appbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.main_appbar = global::XamProjectTemplate.Droid.Resource.Id.main_appbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.main_tablayout = global::XamProjectTemplate.Droid.Resource.Id.main_tablayout;
			global::Xamarin.Forms.Platform.Android.Resource.Id.main_toolbar = global::XamProjectTemplate.Droid.Resource.Id.main_toolbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.main_viewpager = global::XamProjectTemplate.Droid.Resource.Id.main_viewpager;
			global::Xamarin.Forms.Platform.Android.Resource.Id.shellcontent_appbar = global::XamProjectTemplate.Droid.Resource.Id.shellcontent_appbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.shellcontent_toolbar = global::XamProjectTemplate.Droid.Resource.Id.shellcontent_toolbar;
			global::Xamarin.Forms.Platform.Android.Resource.Id.sliding_tabs = global::XamProjectTemplate.Droid.Resource.Id.sliding_tabs;
			global::Xamarin.Forms.Platform.Android.Resource.Id.toolbar = global::XamProjectTemplate.Droid.Resource.Id.toolbar;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.BottomTabLayout = global::XamProjectTemplate.Droid.Resource.Layout.BottomTabLayout;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.FallbackTabbarDoNotUse = global::XamProjectTemplate.Droid.Resource.Layout.FallbackTabbarDoNotUse;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.FallbackToolbarDoNotUse = global::XamProjectTemplate.Droid.Resource.Layout.FallbackToolbarDoNotUse;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.FlyoutContent = global::XamProjectTemplate.Droid.Resource.Layout.FlyoutContent;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.RootLayout = global::XamProjectTemplate.Droid.Resource.Layout.RootLayout;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.ShellContent = global::XamProjectTemplate.Droid.Resource.Layout.ShellContent;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.Tabbar = global::XamProjectTemplate.Droid.Resource.Layout.Tabbar;
			global::Xamarin.Forms.Platform.Android.Resource.Layout.Toolbar = global::XamProjectTemplate.Droid.Resource.Layout.Toolbar;
			global::Xamarin.Forms.Platform.Android.Resource.String.overflow_tab_title = global::XamProjectTemplate.Droid.Resource.String.overflow_tab_title;
			global::Xamarin.Forms.Platform.Android.Resource.Style.AppCompatDialogStyle = global::XamProjectTemplate.Droid.Resource.Style.AppCompatDialogStyle;
			global::Xamarin.Forms.Platform.Android.Resource.Style.collectionViewTheme = global::XamProjectTemplate.Droid.Resource.Style.collectionViewTheme;
			global::Xamarin.Forms.Platform.Android.Resource.Style.MainTheme = global::XamProjectTemplate.Droid.Resource.Style.MainTheme;
			global::Xamarin.Forms.Platform.Android.Resource.Style.MainTheme_Base = global::XamProjectTemplate.Droid.Resource.Style.MainTheme_Base;
			global::Xamarin.Forms.Platform.Android.Resource.Style.scrollViewScrollBars = global::XamProjectTemplate.Droid.Resource.Style.scrollViewScrollBars;
			global::Xamarin.Forms.Platform.Android.Resource.Style.scrollViewTheme = global::XamProjectTemplate.Droid.Resource.Style.scrollViewTheme;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.ItemsViewRendererTheme = global::XamProjectTemplate.Droid.Resource.Styleable.ItemsViewRendererTheme;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.ItemsViewRendererTheme_collectionViewStyle = global::XamProjectTemplate.Droid.Resource.Styleable.ItemsViewRendererTheme_collectionViewStyle;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.ScrollViewRendererTheme = global::XamProjectTemplate.Droid.Resource.Styleable.ScrollViewRendererTheme;
			global::Xamarin.Forms.Platform.Android.Resource.Styleable.ScrollViewRendererTheme_scrollViewStyle = global::XamProjectTemplate.Droid.Resource.Styleable.ScrollViewRendererTheme_scrollViewStyle;
			global::Xamarin.Forms.Platform.Resource.Animation.EnterFromLeft = global::XamProjectTemplate.Droid.Resource.Animation.EnterFromLeft;
			global::Xamarin.Forms.Platform.Resource.Animation.EnterFromRight = global::XamProjectTemplate.Droid.Resource.Animation.EnterFromRight;
			global::Xamarin.Forms.Platform.Resource.Animation.ExitToLeft = global::XamProjectTemplate.Droid.Resource.Animation.ExitToLeft;
			global::Xamarin.Forms.Platform.Resource.Animation.ExitToRight = global::XamProjectTemplate.Droid.Resource.Animation.ExitToRight;
			global::Xamarin.Forms.Platform.Resource.Attribute.collectionViewStyle = global::XamProjectTemplate.Droid.Resource.Attribute.collectionViewStyle;
			global::Xamarin.Forms.Platform.Resource.Attribute.scrollViewStyle = global::XamProjectTemplate.Droid.Resource.Attribute.scrollViewStyle;
			global::Xamarin.Forms.Platform.Resource.Id.bottomtab_navarea = global::XamProjectTemplate.Droid.Resource.Id.bottomtab_navarea;
			global::Xamarin.Forms.Platform.Resource.Id.bottomtab_tabbar = global::XamProjectTemplate.Droid.Resource.Id.bottomtab_tabbar;
			global::Xamarin.Forms.Platform.Resource.Id.flyoutcontent_appbar = global::XamProjectTemplate.Droid.Resource.Id.flyoutcontent_appbar;
			global::Xamarin.Forms.Platform.Resource.Id.main_appbar = global::XamProjectTemplate.Droid.Resource.Id.main_appbar;
			global::Xamarin.Forms.Platform.Resource.Id.main_tablayout = global::XamProjectTemplate.Droid.Resource.Id.main_tablayout;
			global::Xamarin.Forms.Platform.Resource.Id.main_toolbar = global::XamProjectTemplate.Droid.Resource.Id.main_toolbar;
			global::Xamarin.Forms.Platform.Resource.Id.main_viewpager = global::XamProjectTemplate.Droid.Resource.Id.main_viewpager;
			global::Xamarin.Forms.Platform.Resource.Id.shellcontent_appbar = global::XamProjectTemplate.Droid.Resource.Id.shellcontent_appbar;
			global::Xamarin.Forms.Platform.Resource.Id.shellcontent_toolbar = global::XamProjectTemplate.Droid.Resource.Id.shellcontent_toolbar;
			global::Xamarin.Forms.Platform.Resource.Id.sliding_tabs = global::XamProjectTemplate.Droid.Resource.Id.sliding_tabs;
			global::Xamarin.Forms.Platform.Resource.Id.toolbar = global::XamProjectTemplate.Droid.Resource.Id.toolbar;
			global::Xamarin.Forms.Platform.Resource.Layout.BottomTabLayout = global::XamProjectTemplate.Droid.Resource.Layout.BottomTabLayout;
			global::Xamarin.Forms.Platform.Resource.Layout.FallbackTabbarDoNotUse = global::XamProjectTemplate.Droid.Resource.Layout.FallbackTabbarDoNotUse;
			global::Xamarin.Forms.Platform.Resource.Layout.FallbackToolbarDoNotUse = global::XamProjectTemplate.Droid.Resource.Layout.FallbackToolbarDoNotUse;
			global::Xamarin.Forms.Platform.Resource.Layout.FlyoutContent = global::XamProjectTemplate.Droid.Resource.Layout.FlyoutContent;
			global::Xamarin.Forms.Platform.Resource.Layout.RootLayout = global::XamProjectTemplate.Droid.Resource.Layout.RootLayout;
			global::Xamarin.Forms.Platform.Resource.Layout.ShellContent = global::XamProjectTemplate.Droid.Resource.Layout.ShellContent;
			global::Xamarin.Forms.Platform.Resource.Layout.Tabbar = global::XamProjectTemplate.Droid.Resource.Layout.Tabbar;
			global::Xamarin.Forms.Platform.Resource.Layout.Toolbar = global::XamProjectTemplate.Droid.Resource.Layout.Toolbar;
			global::Xamarin.Forms.Platform.Resource.String.overflow_tab_title = global::XamProjectTemplate.Droid.Resource.String.overflow_tab_title;
			global::Xamarin.Forms.Platform.Resource.Style.AppCompatDialogStyle = global::XamProjectTemplate.Droid.Resource.Style.AppCompatDialogStyle;
			global::Xamarin.Forms.Platform.Resource.Style.collectionViewTheme = global::XamProjectTemplate.Droid.Resource.Style.collectionViewTheme;
			global::Xamarin.Forms.Platform.Resource.Style.MainTheme = global::XamProjectTemplate.Droid.Resource.Style.MainTheme;
			global::Xamarin.Forms.Platform.Resource.Style.MainTheme_Base = global::XamProjectTemplate.Droid.Resource.Style.MainTheme_Base;
			global::Xamarin.Forms.Platform.Resource.Style.scrollViewScrollBars = global::XamProjectTemplate.Droid.Resource.Style.scrollViewScrollBars;
			global::Xamarin.Forms.Platform.Resource.Style.scrollViewTheme = global::XamProjectTemplate.Droid.Resource.Style.scrollViewTheme;
			global::Xamarin.Forms.Platform.Resource.Styleable.ItemsViewRendererTheme = global::XamProjectTemplate.Droid.Resource.Styleable.ItemsViewRendererTheme;
			global::Xamarin.Forms.Platform.Resource.Styleable.ItemsViewRendererTheme_collectionViewStyle = global::XamProjectTemplate.Droid.Resource.Styleable.ItemsViewRendererTheme_collectionViewStyle;
			global::Xamarin.Forms.Platform.Resource.Styleable.ScrollViewRendererTheme = global::XamProjectTemplate.Droid.Resource.Styleable.ScrollViewRendererTheme;
			global::Xamarin.Forms.Platform.Resource.Styleable.ScrollViewRendererTheme_scrollViewStyle = global::XamProjectTemplate.Droid.Resource.Styleable.ScrollViewRendererTheme_scrollViewStyle;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7F010000
			public const int EnterFromLeft = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int EnterFromRight = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int ExitToLeft = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ExitToRight = 2130771971;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7F020000
			public const int collectionViewStyle = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int scrollViewStyle = 2130837505;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F030000
			public const int colorAccent = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int colorPrimary = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int colorPrimaryDark = 2130903042;
			
			// aapt resource value: 0x7F030003
			public const int launcher_background = 2130903043;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040000
			public const int bottomtab_navarea = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int bottomtab_tabbar = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int flyoutcontent_appbar = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int main_appbar = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int main_tablayout = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int main_toolbar = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int main_viewpager = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int shellcontent_appbar = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int shellcontent_toolbar = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int sliding_tabs = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int toolbar = 2130968586;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050000
			public const int BottomTabLayout = 2131034112;
			
			// aapt resource value: 0x7F050001
			public const int FallbackTabbarDoNotUse = 2131034113;
			
			// aapt resource value: 0x7F050002
			public const int FallbackToolbarDoNotUse = 2131034114;
			
			// aapt resource value: 0x7F050003
			public const int FlyoutContent = 2131034115;
			
			// aapt resource value: 0x7F050004
			public const int RootLayout = 2131034116;
			
			// aapt resource value: 0x7F050005
			public const int ShellContent = 2131034117;
			
			// aapt resource value: 0x7F050006
			public const int Tabbar = 2131034118;
			
			// aapt resource value: 0x7F050007
			public const int Toolbar = 2131034119;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F060000
			public const int icon = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int icon_round = 2131099649;
			
			// aapt resource value: 0x7F060002
			public const int launcher_foreground = 2131099650;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F070000
			public const int overflow_tab_title = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F080000
			public const int AppCompatDialogStyle = 2131230720;
			
			// aapt resource value: 0x7F080003
			public const int collectionViewTheme = 2131230723;
			
			// aapt resource value: 0x7F080001
			public const int MainTheme = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int MainTheme_Base = 2131230722;
			
			// aapt resource value: 0x7F080004
			public const int scrollViewScrollBars = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int scrollViewTheme = 2131230725;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			// aapt resource value: { 0x7F020000 }
			public static int[] ItemsViewRendererTheme = new int[] {
					2130837504};
			
			// aapt resource value: 0
			public const int ItemsViewRendererTheme_collectionViewStyle = 0;
			
			// aapt resource value: { 0x7F020001 }
			public static int[] ScrollViewRendererTheme = new int[] {
					2130837505};
			
			// aapt resource value: 0
			public const int ScrollViewRendererTheme_scrollViewStyle = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
		
		public partial class Xml
		{
			
			// aapt resource value: 0x7F0A0000
			public const int file_paths = 2131361792;
			
			// aapt resource value: 0x7F0A0001
			public const int xamarin_essentials_fileprovider_file_paths = 2131361793;
			
			static Xml()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Xml()
			{
			}
		}
	}
}
#pragma warning restore 1591
